# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
    # - run: npm test
    #   env:
    #     CI: true
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: qoomon/actions-publish-to-github-pages@v1.0.1
      with:
        GITHUB_PAGES_SOURCE_DIR: dist
        GITHUB_PAGES_BRANCH: gh-pages
        GITHUB_PAGES_REPLACE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
